baseURL = "https://www.windandbones.com"
languageCode = "en-us"
paginate = 12
summaryLength = "30"
theme = "influencer-hugo"
title = "Wind&Bones"
[Social]
facebook = "windandboneseducation"
instagram = "windbones"
twitter = "windandbones"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 7
[[menu.main]]
URL = "review"
name = "Reviews"
weight = 5
[[menu.main]]
URL = "chapter"
name = "Projects"
weight = 4
[[menu.main]]
URL = "device"
name = "Our work"
weight = 3
[[menu.main]]
URL = "author"
name = "About"
weight = 2
[[menu.main]]
URL = "banner"
name = "Home"
weight = 1
[params]
author = "Wind&Bones"
copyright = "&copy; 2021 - 2022 Wind&Bones Community Interest Company. Company registered in Scotland. Company no. SC734907 3/L, 48 Cleghorn Street, Dundee. DD2 2NJ."
description = "Writing and storytelling for social change. We mentor, teach and consult. Run by writers Dr Hannah Stevens & Dr Will Buckingham"
googleAnalitycsID = ""
home = "Home"
image_main = "images/wind-bones.png"
logo = ""
[params.cookies]
enable = true
expire_days = 2
[params.footer]
content = "If you want to get in touch, you can contact Wind&Bones using this form. We will get back to you as soon as we can."
[params.navButton]
enable = true
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/magnific-popup/magnific-popup.min.js"
[params.preloader]
enable = true
preloader = ""
