#-------------------------------
# General Site Settings
baseURL = "/"
languageCode = "en-GB"
title = "滋養台南 | Nourishing Tainan"
paginate = 9

[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  description = "Writing, Creativity, and Social Change"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.

[taxonomies]
  tag = 'tags'


#-------------------------------
# Main Menu
[menu]

  [[menu.main]]
    identifier = "blog"
    name = "故事 ｜ stories"
    url = "/posts/"
    weight = 3

[[menu.main]]
      name = "關於我們 ｜ About"
      url = "/about/"
      weight = 4

[[menu.main]]
      name = "搜尋 ｜ Search"
      url = "/search/"
      weight = 6

[[menu.main]]
      name = "聯絡我們 | Contact Us"
      url = "/contact/"
      weight = 7

      # Footer Menu
      [[menu.footer]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1

      [[menu.footer]]
      identifier = "blog"
      name = "故事｜stories"
      url = "/posts/"
      weight = 3

      [[menu.footer]]
      identifier = "about"
      name = "關於我們｜About"
      url = "/about/"
      weight = 4

      [[menu.footer]]
      identifier = "search"
      name = "搜尋｜Search"
      url = "/search/"
      weight = 4


      [[menu.footer]]
      identifier = "privacy"
      name = "Privacy"
      url = "/privacy/"
      weight = 5

      [[menu.footer]]
      identifier = "contact"
      name = "Contact"
      url = "/contact/"
      weight = 9

  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "Wind&Bones"
    author__bio = "Writing and storytelling for social change. We mentor, teach and consult. Run by writers Dr Hannah Stevens & Dr Will Buckingham. Registered as a social enterprise in Dundee, Scotland, we work across the globe. We currently divide our time between Dundee and Tainan, Taiwan."
    author__avatar = "https://via.placeholder.com/500x500"

  # Social Links
  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com/windandbones"

  [[params.social]]
    icon = "ion-logo-facebook"
    name = "Facebook"
    link = "https://www.facebook.com/windandboneswriting"

  [[params.social]]
    icon = "ion-logo-instagram"
    name = "Instagram"
    link = "https://www.instagram.com/windandboneswriting/"

  # Example of adding a new link to the footer:
  # [[params.social]]
  #   icon = "ion-logo-youtube"
  #   name = "Youtube"
  #   link = "https://youtube.com"

  # Other icons can be found at https://ionicons.com/v4/


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero__title = "滋養台南 | Nourishing Tainan"
    hero__description = "食物滋養我們的身體。故事滋養我們的靈魂。哲學滋養我們的心靈  |  Food Nourishes Our Bodies. Stories nourish our spirit. Philosophy nourishes our mind."
    hero__image = "/images/about/frontpage.jpg"


  #-------------------------------
  # Newsletter Settings
  [params.mailchimp]
    enable = true
    mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__input__text = "Your email address..."
    mailchimp__button__text = "Get updates" # Add your button text


  #-------------------------------
  # Mentoring Settings
  [params.mentor]
    enable = true
    mentor__title= "Mentoring with Wind&Bones"
    mentor__description = "Wind&Bones offer mentoring for writers at all stages of their careers, from absolute beginners to writers with years of experience. Our mentoring packages are designed to work around your needs, so you can reach your writing goals."
    mentor__image = "images/mentor/writer.jpg"

  
  
  #-------------------------------
  
  #-------------------------------
  # Projects Settings
  [params.projects]
    enable = false
    projects__title= "Our Projects"
    projects__description= "We work around the globe on projects exploring the meeting-places between writing, creativity and social change."


  #-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = false
    testimonial__title = "What people are saying"
    testimonial__description = ""

  [[params.testimonial_item]]
    name = "Katie Julian"
    image = "images/client/kt.jpg"
    designation = "Curriculum Manager at Mote Oo Education, Myanmar"
    link = "https://www.moteoo.org/en"
    content = "I cannot recommend Wind&Bones more highly. Aside from their proficiency in bending words to their will and whim, they are also delightful people to work with: warm, witty, caring, with dollops of high-level professionalism. You will not regret time spent working with Hannah and Will."

[[params.testimonial_item]]
    name = "Olia Mineva"
    image = "images/client/olia.png"
    designation = "CEO at Emprove Foundation"
    link = "https://emproveproject.eu/"
    content = "Hannah and Will did not just teach us how to write, they actually made us realise about a secret power we’ve been carrying - the power to change lives and the world we live in through our STORIES. With their amazing dedication, guidance and mentorship we developed a large exhibition at our National Gallery, a powerful deck of story-cards, a series of public readings, workshops and a violence prevention tour."

  [[params.testimonial_item]]
    name = "Konstantinos Achile"
    image = "images/client/kostas.jpg"
    link = "https://amna.org/"
    designation = "Youth Development Lead at Refugee Trauma Initiative"
    content = "We worked together at Refugee Trauma Initiative, running a creative writing workshop in Thessaloniki, Greece with young displaced people. They were amazing, extremely professional and most importantly they knew what they were doing. I highly recommend them!"

  [[params.testimonial_item]]
    name = "Professor Carla Nappi"
    image = "images/client/carla.jpg"
    designation = "Andrew W. Mellon Chair, Department of History, Pittsburgh University."
    link = "https://carlanappi.com/"
    content = "Huge thanks to the Wind&Bones team for helping me through a stuck patch in a fiction writing project.  Will Buckingham and Hannah Stevens are fabulous writing mentors (and just generally awesome and brilliant humans), doing really cool things. Check out their work, y’all."
  
  [[params.testimonial_item]]
    name = "Amjad Mestari"
    image = "images/client/amjad.jpg"
    designation = "Founder, Garage Cultural Centre, Jordan"
    content = "Hannah and Will created an atmosphere which made me — and I think everyone — feel safe and accepted. In the class, I felt appreciated and valued, and overall it was one of the most positive workshops I have ever attended. Also, Hannah and Will are some of the nicest people I’ve ever met – always giving a positive energy."

  [[params.testimonial_item]]
    name = "Grace Susetyo"
    image = "images/client/grace.jpg"
    designation = "Writer and journalist, Indonesia"
    content = "The Wind&Bones mini-course I joined was both a thought-provoking lesson and an inviting space to collaborate with fellow participants. Wind& Bones show writers how to write more ethically, and find that sweet spot between addressing hard issues and telling inspiring stories about humanity."

  [[params.testimonial_item]]
    name = "Dr. Angela Stienne"
    image = "images/client/angela.jpg"
    designation = "Egyptologist and author. Creator of Mummy Stories & The Lyme Museum."
    link = "https://www.angelastienne.com//"
    content = "I’m delighted to have signed up on the Wind&Bones creative writing mentoring programme. It is absolutely lovely. I especially love how well-paced it is, especially in these circumstances. I cannot recommend Will Buckingham & Hannah Stevens enough."
    
 [[params.testimonial_item]]
    name = "Dr. Ariane Karbe"
    image = "images/client/ariane.png"
    designation = "Museologist and writer"
    link = "http://exhibition-telling.com/"
    content = "Publishing your first book can be scary. Wind&Bones helped me with my book proposal: they were friendly, knowledgeable and to the point. What can I say? At this moment, I'm waiting for the first printed copies."
  
  #-------------------------------
  # Blog Section
  [params.blog]
    enable = true
    blog__title = "Recent News"
    blog__description = ""


  #-------------------------------
  # Gallery Footer Settings
  [params.gallery]
    enable = false

  [[params.gallery_image]]
    image_alt = "Rest"
    image_url = "https://via.placeholder.com/800x800"

  [[params.gallery_image]]
    image_alt = "Lifestyle"
    image_url = "https://via.placeholder.com/800x800"

  [[params.gallery_image]]
    image_alt = "Hobby"
    image_url = "https://via.placeholder.com/800x800"

  [[params.gallery_image]]
    image_alt = "Notes"
    image_url = "https://via.placeholder.com/800x800"


  #-------------------------------
  # Contact Settings
  [params.contact]
    contact__email = "your@email.com" # Add your form_id

    # NOTE
    # Hilton theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


  #-------------------------------

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false