######################## default configuration ####################
baseURL = "https://www.windandbones.com"
languageCode = "en-us"
title = "Wind and Bones"
theme = "influencer-hugo"
summaryLength = "30"
paginate = 12
image = "/images/wind-bones.png"

############################# Twtitter ##############################

[twitter]
  card = "summary"
  site = "@windandbones"
  title = "Wind and Bones"
  description = "Writing and storytelling for social change. We mentor, teach and consult. Run by writers Dr Hannah Stevens & Dr Will Buckingham"
  image = "/images/wind-bones.png"

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/magnific-popup/magnific-popup.css"
  
  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/magnific-popup/magnific-popup.min.js"

  
############################## navigation ###############################
[menu]

[[menu.main]]
name = "Home"
URL = "banner"
weight = 1
    
    
    [[menu.main]]
    name = "About us"
    URL = "author"
    weight = 2
    
  [[menu.main]]
  name = "Work with us"
  URL = "device"
  weight = 3
  
  
  [[menu.main]]
  name = "Projects"
  URL = "chapter"
  weight = 4
  
  [[menu.main]]
  name = "Reviews"
  URL = "review"
  weight = 5
  
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 6
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 7


#################### default parameters ################################
[params]
logo = ""
home = "Home"
# Meta data
author = "Wind&Bones"
description = "Writing and storytelling for social change. We mentor, teach and consult. Run by writers Dr Hannah Stevens & Dr Will Buckingham"
twitter_card = true
images = ["images/wind-bones.png"]

# Google Analitycs
googleAnalitycsID = "" # Your ID
# copyright
copyright = "&copy; 2021 Wind&Bones Company 12355764 80 Evesham Rd LE3 2BD UK"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.navButton]
enable = true

# cookies
[params.cookies]
enable = true
expire_days = 2
  
############################# Footer ########################
[params.footer]
content = "If you want to get in touch, you can contact Wind&Bones using this form. We will get back to you as soon as we can."

############################# Social ########################
[Social]
facebook = "windandboneseducation"
instagram = "windbones"
twitter = "windandbones"